Use predict pattern for similarity recommendations
byapparov/recommender pull request #11
Opened 2017-07-04 13:14 UTC by byapparov

2017-07-07 13:26 UTC, lmavridis requested changes

2017-07-07 13:26 UTC, lmavridis commented on R/similarModel.R
> +setClass("similarity.recommender", representation(sim = "matrix"))
`representation` should be avoided from R version 3.0.0 onwards

`setClass("similarity.recommender",  slots = c(sim = "matrix")`

2017-07-07 13:26 UTC, lmavridis commented on R/similarModel.R
> +  if(is.null(filter)) filter <- colnames(m)
Maybe we should include a comment line here ?

2017-07-07 13:26 UTC, lmavridis commented on R/similarModel.R
> +setClass("similarity.recommender", representation(sim = "matrix"))
https://stat.ethz.ch/R-manual/R-devel/library/methods/html/setClass.html

2017-07-07 13:26 UTC, lmavridis commented on R/similarModel.R
> +  target.skus <- intersect(unique(newdata[, sku]), colnames(object@sim))
Check that `target.skus` is not empty ?

2017-07-07 13:26 UTC, lmavridis commented on R/similarModel.R
> +recommendSimilarProducts <- function(model, hits, exclude.same = TRUE,
Why are we moving the data split and logic inside recommender ?

2017-07-07 13:26 UTC, lmavridis commented on R/similarModel.R
> +    if(exclude.same) { # exclude seen products from recommendations
Wondering if its better to write an extra function

2017-07-07 13:26 UTC, lmavridis commented on R/similarProducts.R
> +  by.cols <- setdiff(colnames(dt), c("sku", "sim"))
Is this a new way of passing multiple grouping values ?

2017-07-07 13:26 UTC, lmavridis commented on tests/testthat/helper.similarity.model.R
> +testSimilarityModel <- function() {
Comment

2017-07-07 13:26 UTC, lmavridis commented on tests/testthat/test.similarity.R
> +  expect_equal(as.character(res), c("a", "b"), "We got products from the same group")
Why did this changed ?

2017-07-07 20:32 UTC, byapparov commented on tests/testthat/test.similarity.R
> +  expect_equal(as.character(res), c("a", "b"), "We got products from the same group")
I have made the similarity matrix in the test symmetric, as it supposed to be. otherwise it is confusing.

2017-07-08 09:43 UTC, byapparov commented on R/similarProducts.R
> +  by.cols <- setdiff(colnames(dt), c("sku", "sim"))
here we usually would have 4 columns: `visitor.id`, `sku`, `group`, `sim`. 

So I guess alternative will be setting `by.cols` to `c("visitor.id", "group")`

2017-07-08 09:47 UTC, byapparov commented on R/similarProducts.R
> +  by.cols <- setdiff(colnames(dt), c("sku", "sim"))
I guess I did it this way to simplify the testing

2017-07-08 09:53 UTC, byapparov commented on R/similarModel.R
> +  target.skus <- intersect(unique(newdata[, sku]), colnames(object@sim))
This is covered by test:

```R
  # SKU does not exist in the matrix:
  page.views <-  data.table(visitor.id = c("u1"), sku = c("z"))
  res <- recommendSimilarProducts(test.sim.model, page.views)
  expect_identical(nrow(res), 0L, "Result is empty for the SKU that is not in the similarity model")
```

Here: https://github.com/byapparov/recommender/blob/predict/tests/testthat/test.similarity.model.R

2017-09-09 21:56 UTC, merged